[package]
name = "editor-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "comfy"
path = "src/main.rs"

[dependencies]
crossterm = {version = "0.28.1", features = ["event-stream"]}
tokio = {version = "1.40.0", features = ["rt-multi-thread", "macros", "time"]}
